functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру, бренду.
  - Пользователь должен иметь возможность просматривать товары в каталоге, пользуясь постраничным выводом, и просматривать подробную информацию о товаре. 
    В обоих случаях отображается следующая информация - название, рейтинг, цена со скидкой и без нее.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - После добавления товару в корзину пользователь может продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге.
  - При оформлении заказа осуществляется переход на страницу оплаты. 
  - Корзина хранится в сессии браузера. 
  - Интернет-магазин - это SPA приложение, которое не перезагружает страницу. 

non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах. 

implicit:
  - Сохранение корзины через ckookie-файлы при завершении работы с сайтом пользователем
  - Поиск по хештегу
  - Отображение размера скидки на странице товара.
  - Интерфейс доступен на двух языках - русский и английский.
